services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./settings.yml:/etc/abbey/settings.yml:ro
      - ./.env:/etc/abbey/.env
      - ./file-storage:/app/app/static
    depends_on:
      - redis
      - mysql
      - db_pooler

  # When making any code changes, you must rebuild the frontend.
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./settings.yml:/etc/abbey/settings.yml:ro
      - ./.env:/etc/abbey/.env:ro

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=learn
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    command: celery -A app.worker.celery worker
    volumes:
      - ./backend:/app
      - ./settings.yml:/etc/abbey/settings.yml:ro
      - ./.env:/etc/abbey/.env
      - ./file-storage:/app/app/static
    depends_on:
      - mysql
      - db_pooler
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db_pooler:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    command: python3 -m app.db_pooler
    volumes:
      - ./backend:/app
      - ./settings.yml:/etc/abbey/settings.yml:ro
      - ./.env:/etc/abbey/.env
      - ./file-storage:/app/app/static
    depends_on:
      - redis
      - mysql

  emailer:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    command: python3 -m app.email_process
    volumes:
      - ./backend:/app
      - ./settings.yml:/etc/abbey/settings.yml:ro
      - ./.env:/etc/abbey/.env
      - ./file-storage:/app/app/static
    depends_on:
      - redis
      - mysql
      - db_pooler
    profiles:
      - email

volumes:
  mysql-data:
