services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./settings.yml:/etc/abbey/settings.yml:ro
      - ./.env:/etc/abbey/.env
      - ./file-storage:/app/app/static
      - ./backend/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      - PYTHONUNBUFFERED=true
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend-build
      - ./settings.yml:/etc/abbey/settings.yml:ro
      - ./.env:/etc/abbey/.env:ro
      - /frontend-build/node_modules  # Any modifications to node_modules should be done from inside the container!

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    volumes:
      - ./scraper:/app
      - ./.env:/etc/abbey/.env:ro
      - ./scraper/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - 5006:5006

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=learn
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
