services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./settings.yml:/etc/abbey/settings.yml:ro
      - ./.env:/etc/abbey/.env
      - ./file-storage:/app/app/static
    depends_on:
      - mysql

  # When making any code changes, you must rebuild the frontend.
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=learn
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
